name: CI
on:
  push:
  pull_request:

jobs:
  foundry:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: stable   # recomand stable, nu nightly

      - name: Install dependencies
        run: forge install foundry-rs/forge-std --no-git

      - name: Build
        run: forge build

      - name: Test
        run: forge test -vv
